// src/quickstart/examples/vue/src/SpreadsheetViewer.vue
<template>
	<div ref="sv"></div>
</template>

<style scoped>
	div {
	  height: 600px;
    width: 100%;
    border: 2px dashed #6c82dc;
	}
</style>

<script>
	import {SpreadsheetViewer} from '../../../spreadsheet-viewer/client-library/clientLibrary'

	export default {
		mounted() {
			SpreadsheetViewer({
				container: this.$refs.sv,
				assetsUrl: '../../../spreadsheet-viewer/sv/index.html'
			}).then(instance => {
				instance.configure({
					license: 'evaluation'
				})
				instance.loadWorkbook('../../../common/workbooks/sample-file.xlsx', 0)
			}).catch(console.error)
		}
	}
</script>

// src/quickstart/examples/react/src/SpreadsheetViewer.jsx
import React, { useLayoutEffect, useRef } from 'react';

import { SpreadsheetViewer } from '../../../spreadsheet-viewer/client-library/clientLibrary';

export default () => {
  const svRef = useRef(null);

  // `useLayoutEffect` is the same as `useEffect`, but the callback inside
  // always gets executed after all DOM mutations, meaning that `svRef.current`
  // will always be populated.
  useLayoutEffect(() => {
    SpreadsheetViewer({
      assetsUrl: '../../../spreadsheet-viewer/sv/index.html',
      container: svRef.current
    })
      .then((instance) => {
        instance.configure({
          license: 'demo'
        });

        instance.loadWorkbook('../../../common/workbooks/sample-file.xlsx', 0);
      })
      .catch(console.error);
  }, []);

  return (
    <div key="spreadsheet-viewer" id="spreadsheet-viewer" ref={svRef} />
  );
};
